# Site setings
name: 'goldenthumb'
description: 'Web Developer'
meta_description: 'web develop'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'logo.png'
  greetings: "web develop blog"
favicon: 'assets/images/favicon.png'
baseurl: 
production_url: https://goldenthumb.net/
disqus: 'goldenthumb'
mailchimp_url:
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: cyh8914@gamil.com
contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
facebook: 'godenthumb'
github: 'goldenthumb'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
